server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db2022?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

eureka:
  client:
    # 向 eureka注册中心 注册自己
    register-with-eureka: true
    # 是否从 eureka服务 抓取注册信息
    fetchRegistry: true
    service-url:
      # 查询服务和注册服务都需要依赖这个地址
      #单机版 http://${eureka.instance.hostname}:${server.port}/eureka/
      #defaultZone: http://localhost:7001/eureka/
      #集群版
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: payment8001
    prefer-ip-address: true # 访问有IP提示
    # 收到最后一次心跳后等待上线 默认90秒 超时剔除服务
    #lease-expiration-duration-in-seconds: 2
    #发送心跳 时间间隔 默认30秒
    #lease-renewal-interval-in-seconds: 1

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.aiteguigu.springcloud.entities